[package]
name = "a78tool"
version.workspace = true
edition.workspace = true
description = "Atari 7800 .a78 ROM header utility adhering to the 8BitDev specification"
license = "MIT"

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[package.metadata.deb]
maintainer = "John Sohn <john.sohn@gmail.com>"
copyright = "2026 John Sohn"
extended-description = "Atari 7800 .a78 ROM header generator, inspector, and stripper."
section = "utils"
priority = "optional"
assets = [
    ["target/release/a78tool", "usr/bin/a78tool", "755"],
    ["../README.md", "usr/share/doc/a78tool/README.md", "644"],
    ["../LICENSE", "usr/share/doc/a78tool/LICENSE", "644"],
]

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/a78tool", dest = "/usr/bin/a78tool", mode = "0755" },
    { source = "../README.md", dest = "/usr/share/doc/a78tool/README.md", mode = "0644" },
    { source = "../LICENSE", dest = "/usr/share/doc/a78tool/LICENSE", mode = "0644" }
]

[lints]
workspace = true
